# Generated by Django 4.0 on 2022-07-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_tag_news_hashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
