# Generated by Django 4.0 on 2022-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('plan', models.ImageField(blank=True, default='static/img/default_plan.jpg', null=True, upload_to='plan/%Y/%m/%d', verbose_name='plan of the accommodation')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена')),
                ('quantity', models.CharField(choices=[('one', '1-комнатная'), ('two', '2-комнатная'), ('thr', '3-комнатная'), ('lrg', '4-комнатная'), ('ext', '5-комнатная')], default='one', max_length=3, verbose_name='кол-во комнат')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
                ('plan', models.ImageField(blank=True, default='static/img/default_plan.jpg', null=True, upload_to='plan/%Y/%m/%d', verbose_name='plan of the accommodation')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена')),
                ('type_acc', models.CharField(choices=[('std', 'студия'), ('std', 'стандартная'), ('hfl', 'высокие потолки'), ('dpx', 'двухуровневая')], max_length=3, verbose_name='тип помещения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
