# Generated by Django 4.0 on 2022-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0002_accommodation_delete_room_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='quantity',
            field=models.CharField(choices=[('one', '1-комнатная'), ('two', '2-комнатная'), ('thr', '3-комнатная'), ('lrg', '4-комнатная'), ('ext', '5-комнатная')], default='one', max_length=3, verbose_name='кол-во комнат'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='type_acc',
            field=models.CharField(choices=[('std', 'студия'), ('std', 'стандартная'), ('hfl', 'высокие потолки'), ('dpx', 'двухуровневая')], default='std', max_length=3, verbose_name='тип помещения'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
