# Generated by Django 4.0 on 2022-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0003_accommodation_quantity_accommodation_type_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='apartment_complex',
            field=models.CharField(choices=[('C', 'ЖК Центральный'), ('R', 'ЖК Речник'), ('P', 'ЖК Парковый')], default=None, max_length=1, verbose_name='жилой комплекс'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='floor',
            field=models.PositiveIntegerField(default=3, verbose_name='этаж'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='square',
            field=models.PositiveIntegerField(default=None, verbose_name='площадь'),
        ),
    ]
