# Generated by Django 4.0 on 2022-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0005_alter_accommodation_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='quantity',
            field=models.CharField(choices=[('zro', 'без спальни'), ('one', '1-комнатная'), ('two', '2-комнатная'), ('thr', '3-комнатная'), ('lrg', '4-комнатная'), ('ext', '5-комнатная')], default='one', max_length=3, verbose_name='кол-во комнат'),
        ),
    ]
