# Generated by Django 4.0 on 2022-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0009_alter_accommodation_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title'], 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AddField(
            model_name='image',
            name='accommodation',
            field=models.ManyToManyField(related_name='images', to='app_apartments.Accommodation', verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default_flat.jpg', null=True, upload_to='gallery/%Y/%m/%d', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='plan',
            field=models.ImageField(blank=True, default='static/img/default_plan.jpg', null=True, upload_to='plan/%Y/%m/%d', verbose_name='план квартиры'),
        ),
    ]
