# Generated by Django 4.0 on 2022-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0012_remove_image_accommodation_accommodation_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='скидка'),
        ),
    ]
