# Generated by Django 4.0 on 2022-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0016_rename_s_discount_accommodation_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='является активной'),
        ),
    ]
