# Generated by Django 4.0 on 2022-07-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0017_accommodation_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='является активной'),
        ),
        migrations.CreateModel(
            name='ResidenceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=1, verbose_name='жилой комплекс')),
                ('slug', models.SlugField()),
                ('gallery', models.ManyToManyField(related_name='residences', to='app_apartments.Image', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
                'ordering': ('title',),
            },
        ),
    ]
