# Generated by Django 4.0 on 2022-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0018_alter_accommodation_options_remove_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencearea',
            name='title',
            field=models.CharField(choices=[('C', 'ЖК Центральный'), ('R', 'ЖК Речник'), ('P', 'ЖК Парковый')], default='C', max_length=1, verbose_name='жилой комплекс'),
        ),
    ]
