# Generated by Django 4.0 on 2022-07-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0019_alter_residencearea_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='app_apartments.residencearea'),
            preserve_default=False,
        ),
    ]
