# Generated by Django 4.0 on 2022-07-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0020_accommodation_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencearea',
            name='map',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='карта'),
        ),
    ]
