# Generated by Django 4.0 on 2022-07-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0022_residencearea_bank_residencearea_cinema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.SmallIntegerField(default=0, verbose_name='школы')),
                ('kindergarten', models.SmallIntegerField(default=0, verbose_name='дет.сад')),
                ('bank', models.SmallIntegerField(default=0, verbose_name='банки')),
                ('post', models.SmallIntegerField(default=0, verbose_name='почта')),
                ('shop', models.SmallIntegerField(default=0, verbose_name='магазин')),
                ('spy', models.SmallIntegerField(default=0, verbose_name='салоны красоты')),
                ('swimming_pool', models.SmallIntegerField(default=0, verbose_name='бассейн')),
                ('fitness_club', models.SmallIntegerField(default=0, verbose_name='спортзал')),
                ('park', models.SmallIntegerField(default=0, verbose_name='парки,скверы')),
                ('cinema', models.SmallIntegerField(default=0, verbose_name='кино, театры')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
            },
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='fitness_club',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='kindergarten',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='park',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='post',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='school',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='spy',
        ),
        migrations.RemoveField(
            model_name='residencearea',
            name='swimming_pool',
        ),
        migrations.AddField(
            model_name='residencearea',
            name='infrastructure',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='app_apartments.infrastructure'),
        ),
    ]
