# Generated by Django 4.0 on 2022-07-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0023_infrastructure_remove_residencearea_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencearea',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='residence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='app_apartments.residencearea', verbose_name='ЖК'),
        ),
    ]
