# Generated by Django 4.0 on 2022-07-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0024_remove_residencearea_infrastructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='app_apartments.residencearea'),
        ),
    ]
