# Generated by Django 4.0 on 2022-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0025_alter_accommodation_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='gallery',
            field=models.ManyToManyField(related_name='accommodations_gallery', to='app_apartments.Image', verbose_name='изображение'),
        ),
    ]
