# Generated by Django 4.0 on 2022-07-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0027_residencearea_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='swimming_pool',
        ),
    ]
