# Generated by Django 4.0 on 2022-08-26 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0029_itemview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 6, 45, 13, 20092)),
        ),
    ]
