# Generated by Django 4.0 on 2022-08-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0030_alter_itemview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 6, 57, 15, 707270)),
        ),
    ]
