# Generated by Django 4.0 on 2022-08-26 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0031_alter_itemview_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 6, 58, 38, 65441, tzinfo=utc)),
        ),
    ]
