# Generated by Django 4.0 on 2022-08-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0033_alter_itemview_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemview',
            name='created',
        ),
    ]
