# Generated by Django 4.0 on 2022-08-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apartments', '0034_remove_itemview_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemView',
            new_name='AccommodationView',
        ),
    ]
